services:
  - type: web
    name: my-cpp-app
    env: static
    buildCommand: |
      sudo apt-get update
      sudo apt-get install -y build-essential g++ libopencv-dev
      g++ -o seam_carving seam_carving.cpp `pkg-config --cflags --libs opencv4`
    startCommand: ./seam_carving
    port: 3000  # Use this if your app listens on a port

